[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font.bold]
family = "BerkeleyMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "BerkeleyMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "BerkeleyMono Nerd Font Mono"
style = "Regular"
