#!/bin/bash
#!/bin/giy

zetdir='Repositories/me/zet/'
myzetdir="$HOME/$zetdir"
isosec=$(date -u +%Y%m%d%H%M%S)

currentdir=$(pwd)
cd $myzetdir
mkdir $isosec
cd $isosec
touch README.md
vi README.md
wait
git add *
git commit -m "($isosec) $(grep "## " README.md)"
git push origin master
cd $currentdir
