#!/bin/bash
RED='\033[0;31m'
NOCOLOR='\033[0m'
ghnodepref='https://github.com/sbecerek/me/tree/master/zet/'
merepo='https://github.com/sbecerek/me.git'
zetdir='Repositories/me/zet/'
myzetdir="$HOME/$zetdir"
isosec=$(date -u +%Y%m%d%H%M%S)

createNote(){
	currentdir=$(pwd)
	cd $myzetdir
	git pull origin master;
	mkdir $isosec
	cd $isosec
	if [[ ! -z $@ ]];
		then 
			echo "## $@" >> README.md; 
	else
		touch README.md
	fi
	vi README.md
	wait
	if [[ ! -s README.md ]]; then
		cd ..
		rm -r $isosec
	fi
	if [[ `git status --porcelain` ]]; then
		git add *;
		git commit -m "($isosec) $(grep "## " README.md)";
		git push origin master > /dev/null 2>&1;
		echo "Display your note at $ghnodepref/$isosec"
	fi
	cd $currentdir
}

findNote(){
	currentdir=$(pwd)
	cd $myzetdir
	foundisosecs=$(grep -R $1 . | awk '{print substr($1,3,14)}' | uniq)
	selectedNote='';
	cnt=0
	while true; do
		echo $selectedNote
		for isosec in $foundisosecs
		do
		if grep -q $isosec <<< $selectedNote; then
			echo -e "${RED}$cnt${NOCOLOR}) $isosec - $(grep "## " $isosec/README.md)"
		else
			echo "$cnt) $isosec - $(grep "## " $isosec/README.md)"
		fi
                ((cnt=$cnt+1));
		done

		printf "Select note,\n\t E/e to edit,\n\t O/o to open in browser,\n\t C/c to copy Markdown link,\n\t press N/n to continue: "
		read note
			case $note in
				[Oo])
					openNote $selectedNote
					;;
				[Cc])
					copyMarkdownLink $selectedNote
					;;
				[Ee])
					editNote $selectedNote
					;;
				[Nn*])
					exit 0
					;;
			esac
			case $(( (note >= 0 && note < $cnt)* 1)) in
				(1)
					isosecs=($(echo $foundisosecs | tr " " "\n"))
			                selectedNote="${isosecs[note]}"
					cnt=0;
					;;
				
				?)
					echo "Inserted value is not enumerated option or recognized"
					exit 1
					;;
			esac
	done
	cd $currentdir
}


copyMarkdownLink(){
	echo "Copying Github Link to Clipboard as Markdown"
	echo -n "[$@ - $(grep "## " $@/README.md)]($ghnodepref$@)" | xclip -selection c
}

openNote(){
	echo "Opening $ghnodepref/$@";
	xdg-open $ghnodepref/$@;
}

editNote(){
	currentdir=$(pwd)
	cd $myzetdir
	vi $@/README.md
	wait;
	if [[ `git status --porcelain` ]]; then
		git add *;
		git commit -m "($@) $(grep "## " $1/README.md)";
		git push origin master > /dev/null 2>&1 ;
		echo "Display your note at $ghnodepref/$@"
	fi
	cd $currentdir
}

if [[ ! -d "$myzetdir" ]]; then
	currentdir=$(pwd)
	echo "Need to clone your zet/me repository first";
	cd $HOME/Repositories
	git clone $merepo
	wait;
	cd currentdir
fi

while getopts "c:e:f:" OPTION
do
        case $OPTION in
		e)
		editNote $OPTARG
		exit 0;
		;;
		f)
		findNote $OPTARG
		exit 0
		;;
                c)
                createNote $OPTARG
                exit 0
                ;;
		?)
		echo "Please specify some arguments, I don't know what any of the $@ means"
		exit -1
		;;
        esac
done
