#!/bin/bash

zetdir='Repositories/me/zet/'
myzetdir="$HOME/$zetdir"
isosec=$(date -u +%Y%m%d%H%M%S)

createNote(){
	currentdir=$(pwd)
	cd $myzetdir
	git pull origin master;
	mkdir $isosec
	cd $isosec
	if [ -f ${@:-""} ];
		#echo $@
		then echo "## $@" >> README.md; 
	else
		touch README.md
	fi
	vi README.md
	wait
	git add *;
	git commit -m "($isosec) $(grep "## " README.md)";
	git push origin master;
	cd $currentdir
}

findNote(){
	currentdir=$(pwd)
	cd $myzetdir
	foundisosecs=$(grep -R $OPTARG . | awk '{print substr($1,3,14)}' | uniq)
	#echo $foundisosecs
	cnt=0
	for isosec in $foundisosecs
	do
		echo "$cnt) $isosec - $(grep "## " $isosec/README.md)"
		((cnt=cnt+1));
	done
	cd $currentdir
}

editNote(){
	currentdir=$(pwd)
	cd $myzetdir
	vi $@/README.md
	wait;
	git add *;
	git commit -m "($@) $(grep "## " ./$1/README.md)";
	git push origin master;
	cd $currentdir
}


while getopts "e:f:c" OPTION
do
        case $OPTION in
		e)
		editNote $OPTARG
		exit 0;
		;;
		f)
		findNote $OPTARG
		exit 0
		;;
                c)
                createNote $OPTARG
                exit 0
                ;;
		?)
		echo "Please specify some arguments, I don't 				know what any of the $@ means"
		exit -1
		;;
        esac
done
